#
# Main - Makefile
# @author Arnaud Hincelin
# Organisation des sources.


all: 
	@echo ---------------compilation Telco-----------------
	make -C telco
	@echo ---------------compilation Commando-----------------
	make -C commando


clean:
	@echo ---------------nettoyage Telco-----------------
	make clean -C telco
	@echo ---------------nettoyage Commando-----------------
	make clean -C commando


